### ISSUE TITLE
AKS VMs should respect Hyper-V default folder structure

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#34]
**Title**:
AKS VMs should respect Hyper-V default folder structure

**Description**:
In Hyper-V, there is a folder with VMName and then folders for Configuration (Virtual Machines) and for storage (Virtual Hard Disks). It would be nice, if AKS VMs would use the same.

Currently is VHD outside VM folder.

![image](https://user-images.githubusercontent.com/9829838/94251906-8182e980-ff23-11ea-8753-e5ca39756e3c.png)

![image](https://user-images.githubusercontent.com/9829838/94251945-90699c00-ff23-11ea-94db-91c68f3265a5.png)

![image](https://user-images.githubusercontent.com/9829838/94251960-93fd2300-ff23-11ea-84cb-b3d08c67f8f1.png)

![image](https://user-images.githubusercontent.com/9829838/94251986-9a8b9a80-ff23-11ea-82d3-e9c6eaecf024.png)

**Comment by mkostersitz** [comment]
@jaromirk 
Thank you for testing and your valuable feedback
If I understand this request correctly, you are expecting a folder structure like
`VMName
 |--Configuration
   |--configfiles
 |--Storage
   |--VHD files`
The way we store VHDs right now is by Design because it allows us to have one path for all VHDs in the AKS-HCI system instead of having to traverse a folder structure to find the VHD file when we move VHDs from node to node.
we recommend using the MOC stack to manage AKS-HCI VMs and not use other tools to monitor the folder structure as the behavior will change in future releases. 

I will resolve this as by Design. If you feel this is in error or there are other reasons you are expecting a different structure please let me know
/ByDesign
